### ISSUE TITLE
matemaker and sspace

### ISSUE THREAD

**Issue by ferrojm** [josephryan/matemaker#1]
Hello Joseph, thank you so much for this amazing approach!!!

I have a question regarding the output reads orientation, although you have explained in the description...
When using Sspace, the correct orientation when using should be FF, right?

Thanks again!

Juan

**Comment by josephryan** [comment]
Hello Juan, The orientation should be RF.  I've added a section to the README file named "HOW I USUALLY RUN IT," which includes a subsection "Corresponding SSPACE config file." Hopefully, that would be helpful.  Feel free to post more issues if you need additional help.

**Comment by ferrojm** [comment]
Perfect, thank you for your help!
